{% set name = "blake3" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a78908b6299fd21dd46eb00fa4592b259ee419d586d545a3b86e1f2e4d0ee6d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
  host:
    - maturin
    - pip
    - python
    - toml
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - blake3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oconnor663/blake3-py
  summary: Python bindings for the Rust blake3 crate
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/arrayref-LICENSE-BSD
    - library_licenses/arrayvec-LICENSE-APACHE
    - library_licenses/arrayvec-LICENSE-MIT
    - library_licenses/autocfg-LICENSE-APACHE
    - library_licenses/autocfg-LICENSE-MIT
    - library_licenses/bitflags-LICENSE-APACHE
    - library_licenses/bitflags-LICENSE-MIT
    - library_licenses/blake3-LICENSE-APACHE
    - library_licenses/blake3-LICENSE-APACHE
    - library_licenses/BLAKE3-LICENSE-CC0
    - library_licenses/cc-LICENSE-APACHE
    - library_licenses/cc-LICENSE-MIT
    - library_licenses/cfg-if-LICENSE-APACHE
    - library_licenses/cfg-if-LICENSE-MIT
    - library_licenses/cfg-if-LICENSE-APACHE
    - library_licenses/cfg-if-LICENSE-MIT
    - library_licenses/constant_time_eq-LICENSE-CC0
    - library_licenses/crossbeam-channel-LICENSE-APACHE
    - library_licenses/crossbeam-channel-LICENSE-MIT
    - library_licenses/crossbeam-deque-LICENSE-APACHE
    - library_licenses/crossbeam-deque-LICENSE-MIT
    - library_licenses/crossbeam-epoch-LICENSE-APACHE
    - library_licenses/crossbeam-epoch-LICENSE-MIT
    - library_licenses/crossbeam-utils-LICENSE-APACHE
    - library_licenses/crossbeam-utils-LICENSE-MIT
    - library_licenses/traits-LICENSE-APACHE
    - library_licenses/ctor-LICENSE-APACHE
    - library_licenses/ctor-LICENSE-MIT
    - library_licenses/either-LICENSE-APACHE
    - library_licenses/either-LICENSE-MIT
    - library_licenses/generic-array-LICENSE-MIT
    - library_licenses/ghost-LICENSE-APACHE
    - library_licenses/ghost-LICENSE-MIT
    - library_licenses/hermit-abi-LICENSE-APACHE
    - library_licenses/hermit-abi-LICENSE-MIT
    - library_licenses/hex-LICENSE-APACHE
    - library_licenses/hex-LICENSE-MIT
    - library_licenses/indoc-LICENSE-APACHE
    - library_licenses/indoc-LICENSE-MIT
    - library_licenses/indoc-impl-LICENSE-APACHE
    - library_licenses/indoc-impl-LICENSE-MIT
    - library_licenses/instant-LICENSE-BSD
    - library_licenses/inventory-LICENSE-APACHE
    - library_licenses/inventory-LICENSE-MIT
    - library_licenses/inventory-impl-LICENSE-APACHE
    - library_licenses/inventory-impl-LICENSE-MIT
    - library_licenses/lazy_static-LICENSE-APACHE
    - library_licenses/lazy_static-LICENSE-MIT
    - library_licenses/libc-LICENSE-APACHE
    - library_licenses/libc-LICENSE-MIT
    - library_licenses/lock_api-LICENSE-APACHE
    - library_licenses/lock_api-LICENSE-MIT
    - library_licenses/memoffset-LICENSE-MIT
    - library_licenses/num_cpus-LICENSE-APACHE
    - library_licenses/num_cpus-LICENSE-MIT
    - library_licenses/parking_lot-LICENSE-APACHE
    - library_licenses/parking_lot-LICENSE-MIT
    - library_licenses/parking_lot_core-LICENSE-APACHE
    - library_licenses/parking_lot_core-LICENSE-MIT
    - library_licenses/paste-LICENSE-APACHE
    - library_licenses/paste-LICENSE-MIT
    - library_licenses/paste-impl-LICENSE-APACHE
    - library_licenses/paste-impl-LICENSE-MIT
    - library_licenses/proc-macro-hack-LICENSE-APACHE
    - library_licenses/proc-macro-hack-LICENSE-MIT
    - library_licenses/proc-macro2-LICENSE-APACHE
    - library_licenses/proc-macro2-LICENSE-MIT
    - library_licenses/pyo3-LICENSE-APACHE
    - library_licenses/pyo3-derive-backend-LICENSE-APACHE
    - library_licenses/pyo3cls-LICENSE-APACHE
    - library_licenses/quote-LICENSE-APACHE
    - library_licenses/quote-LICENSE-MIT
    - library_licenses/rayon-LICENSE-APACHE
    - library_licenses/rayon-LICENSE-MIT
    - library_licenses/rayon-core-LICENSE-APACHE
    - library_licenses/rayon-core-LICENSE-MIT
    - library_licenses/redox_syscall-LICENSE-MIT
    - library_licenses/scopeguard-LICENSE-APACHE
    - library_licenses/scopeguard-LICENSE-MIT
    - library_licenses/smallvec-LICENSE-APACHE
    - library_licenses/smallvec-LICENSE-MIT
    - library_licenses/subtle-LICENSE-BSD
    - library_licenses/syn-LICENSE-APACHE
    - library_licenses/syn-LICENSE-MIT
    - library_licenses/typenum-LICENSE-APACHE
    - library_licenses/typenum-LICENSE-MIT
    - library_licenses/unicode-xid-LICENSE-APACHE
    - library_licenses/unicode-xid-LICENSE-MIT
    - library_licenses/unindent-LICENSE-APACHE
    - library_licenses/unindent-LICENSE-MIT
    - library_licenses/version_check-LICENSE-APACHE
    - library_licenses/version_check-LICENSE-MIT
    - library_licenses/winapi-LICENSE-APACHE
    - library_licenses/winapi-LICENSE-MIT
    - library_licenses/winapi-i686-pc-windows-gnu-LICENSE-APACHE
    - library_licenses/winapi-i686-pc-windows-gnu-LICENSE-MIT
    - library_licenses/winapi-x86_64-pc-windows-gnu-LICENSE-APACHE
    - library_licenses/winapi-x86_64-pc-windows-gnu-LICENSE-MIT
extra:
  recipe-maintainers:
    - maartenbreddels
    - oconnor663
