{% set name = "blake3" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0625c8679203d5a1d30f859696a3fd75b2f50587984690adab839ef112f4c043

build:
  number: 0
  script: 
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.14,<0.15
    - pip
    - python
    - toml
  run:
    - python

test:
  imports:
    - blake3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oconnor663/blake3-py
  summary: Python bindings for the Rust blake3 crate
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - maartenbreddels
    - oconnor663
